// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var ufo, ufoSpeed, gPreload, gCreate, gUpdate, gRender, g;
  ufoSpeed = 200;
  gPreload = function(){
    g.world.setBounds(0, 0, 800, 600);
    g.load.image('ufo', '../../../phaser/examples/assets/sprites/ufo.png');
  };
  gCreate = function(){
    ufo = g.add.sprite(320, 240, 'ufo');
    ufo.anchor.setTo(0.5, 0.5);
    GameController.init({
      left: {
        type: 'joystick',
        joystick: {
          touchStart: function(){},
          touchMove: function(joystickDetails){
            return g.input.joystickLeft = joystickDetails;
          },
          touchEnd: function(){
            return g.input.joystickLeft = null;
          }
        }
      },
      right: {
        type: 'none'
      }
    });
  };
  gUpdate = function(){
    var x, y;
    if (g.input.joystickLeft) {
      x = g.input.joystickLeft.normalizedX * 200;
      y = g.input.joystickLeft.normalizedY * ufoSpeed * -1;
      ufo.body.velocity.setTo(x, y);
    } else {
      ufo.body.velocity.setTo(0, 0);
    }
  };
  gRender = function(){
    g.debug.renderText('Use the virtual joystick to move the UFO.', 20, 20);
    g.debug.renderText('This requires touch events, so try on your phone.', 20, 40);
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
