// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, emitter, gPreload, gCreate, gUpdate, gRender, particleBurst, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.image('diamond', assets + 'sprites/diamond.png');
  };
  gCreate = function(){
    g.stage.backgroundColor = '#337799';
    emitter = g.add.emitter(0, 0, 200);
    emitter.makeParticles('diamond');
    emitter.gravity = 200;
    g.input.onDown.add(particleBurst, this);
  };
  gUpdate = function(){};
  gRender = function(){};
  particleBurst = function(){
    emitter.x = g.input.x;
    emitter.y = g.input.y;
    return emitter.start(true, 2000, null, 10);
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
