// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, bg, filter;
  game = new Phaser.Game(800, 600, Phaser.WEBGL, '', {
    preload: preload,
    create: create,
    update: update
  });
  function preload(){
    game.load.image('phaser', 'assets/sprites/phaser2.png');
    game.load.image('texture', 'assets/textures/ooze.png');
    return game.load.script('filter', 'filters/Tunnel.js');
  }
  function create(){
    var logo;
    bg = game.add.sprite(0, 0, 'texture');
    bg.width = 800;
    bg.height = 600;
    filter = game.add.filter('Tunnel', 800, 600, bg.texture);
    filter.origin = 1.0;
    bg.filters = [filter];
    logo = game.add.sprite(game.world.centerX, game.world.centerY, 'phaser');
    return logo.anchor.setTo(0.5, 0.5);
  }
  function update(){
    filter.update();
    return filter.origin += 0.001;
  }
}).call(this);
