// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, filters, filter, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  filters = '../../../phaser/filters/';
  gPreload = function(){
    g.load.image('phaser', assets + 'sprites/phaser.png');
    g.load.image('texture', assets + 'textures/ooze.png');
    g.load.script('filter', filters + 'Tunnel.js');
  };
  gCreate = function(){
    var bg, logo;
    bg = g.add.sprite(0, 0, 'texture');
    bg.width = 800;
    bg.height = 600;
    filter = g.add.filter('Tunnel', 800, 600, bg.texture);
    filter.origin = 1.0;
    bg.filters = [filter];
    logo = g.add.sprite(g.world.centerX, g.world.centerY, 'phaser');
    logo.anchor.setTo(0.5, 0.5);
  };
  gUpdate = function(){
    filter.update();
  };
  gRender = function(){};
  g = new Phaser.Game(800, 600, Phaser.WEBGL, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
