// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, emitterFront, emitterMid, emitterBack, max, updateInterval, i, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  max = 0;
  updateInterval = 4 * 60;
  i = 0;
  gPreload = function(){
    g.load.spritesheet('snowflakes', assets + 'sprites/snowflakes.png', 17, 17);
    g.load.spritesheet('snowflakes-large', assets + 'sprites/snowflakes_large.png', 64, 64);
  };
  gCreate = function(){
    var emitterBack, emitterMid, emitterFront;
    emitterBack = g.add.emitter(g.world.centerX, -32, 600);
    emitterBack.makeParticles('snowflakes', [0, 1, 2, 3, 4, 5]);
    emitterBack.maxParticleScale = 0.6;
    emitterBack.minParticleScale = 0.2;
    emitterBack.setYSpeed(20, 100);
    emitterBack.gravity = 0;
    emitterBack.width = g.world.width * 1.5;
    emitterBack.minRotation = 0;
    emitterBack.maxRotation = 40;
    emitterMid = g.add.emitter(g.world.centerX, -32, 250);
    emitterMid.makeParticles('snowflakes', [0, 1, 2, 3, 4, 5]);
    emitterMid.maxParticleScale = 1.2;
    emitterMid.minParticleScale = 0.8;
    emitterMid.setYSpeed(50, 150);
    emitterMid.gravity = 0;
    emitterMid.width = g.world.width * 1.5;
    emitterMid.minRotation = 0;
    emitterMid.maxRotation = 40;
    emitterFront = g.add.emitter(g.world.centerX, -32, 50);
    emitterFront.makeParticles('snowflakes-large', [0, 1, 2, 3, 4, 5]);
    emitterFront.maxParticleScale = 1;
    emitterFront.minParticleScale = 0.5;
    emitterFront.setYSpeed(100, 200);
    emitterFront.gravity = 0;
    emitterFront.width = g.world.width * 1.5;
    emitterFront.minRotation = 0;
    emitterFront.maxRotation = 40;
    emitterBack.start(false, 14000, 20);
    emitterMid.start(false, 12000, 40);
    emitterFront.start(false, 6000, 1000);
  };
  gUpdate = function(){};
  gRender = function(){};
  g = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
