// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, handle1, handle2, handle3, handle4, line1, line2, c, p, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  c = 'hsl(0,0%,100%)';
  p = new Phaser.Point();
  gPreload = function(){
    g.load.spritesheet('balls', assets + 'sprites/balls.png', 17, 17);
  };
  gCreate = function(){
    g.stage.backgroundColor = '#124184';
    handle1 = g.add.sprite(100, 200, 'balls', 0);
    handle1.inputEnabled = true;
    handle1.input.enableDrag(true);
    handle2 = g.add.sprite(400, 300, 'balls', 0);
    handle2.inputEnabled = true;
    handle2.input.enableDrag(true);
    handle3 = g.add.sprite(200, 400, 'balls', 1);
    handle3.inputEnabled = true;
    handle3.input.enableDrag(true);
    handle4 = g.add.sprite(500, 500, 'balls', 1);
    handle4.inputEnabled = true;
    handle4.input.enableDrag(true);
    line1 = new Phaser.Line(handle1.x, handle1.y, handle2.x, handle2.y);
    line2 = new Phaser.Line(handle3.x, handle3.y, handle4.x, handle4.y);
  };
  gUpdate = function(){
    line1.fromSprite(handle1, handle2, true);
    line2.fromSprite(handle3, handle4, true);
    p = line1.intersects(line2, true);
    if (p) {
      c = 'hsl(120,100%,50%)';
    } else {
      c = 'hsl(0,0%,100%)';
    }
  };
  gRender = function(){
    g.debug.renderLine(line1, c);
    g.debug.renderLine(line2, c);
    g.debug.renderLineInfo(line1(32, 32));
    g.debug.renderLineInfo(line2(32, 100));
    if (p) {
      g.context.fillStyle = 'hsl(300,100%,50)';
      g.context.fillRect(p.x - 2, p.y - 2, 5, 5);
    }
    g.debug.renderText("Drag the handles", 32, 550);
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
