// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    create: create
  });
  function create(){
    var g, i$, i;
    g = game.add.graphics(0, 0);
    g.beginFill(0xff3300);
    g.lineStyle(10, 0xffd900, 1);
    g.moveTo(0, 50);
    g.lineTo(250, 50);
    g.lineTo(100, 100);
    g.lineTo(250, 220);
    g.lineTo(50, 220);
    g.lineTo(0, 50);
    g.endFill();
    g.lineStyle(10, 0xFF0000, 0.8);
    g.beginFill(0xFF700B, 1);
    g.moveTo(210, 300);
    g.lineTo(450, 320);
    g.lineTo(570, 350);
    g.lineTo(580, 20);
    g.lineTo(330, 120);
    g.lineTo(410, 200);
    g.lineTo(210, 300);
    g.endFill();
    for (i$ = 0; i$ < 25; ++i$) {
      i = i$;
      g.lineStyle(2, 'hsla(240,100%,50%,0.5)', 1);
      g.drawRect(50 + i * 10, 250 + i * 10, 100, 100);
    }
    g.lineStyle(0);
    g.beginFill(0xFFFF0B, 0.5);
    g.drawCircle(470, 200, 100);
    g.lineStyle(20, 0x33FF00);
    g.moveTo(600, 150);
    return g.lineTo(30, 450);
  }
}).call(this);
