// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, emitterLeft, emitterRight, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.image('ball1', assets + 'sprites/red_ball.png');
    g.load.image('ball2', assets + 'sprites/blue_ball.png');
  };
  gCreate = function(){
    emitterLeft = g.add.emitter(50, g.world.centerY - 200);
    emitterLeft.bounce.setTo(0.5, 0.5);
    emitterLeft.setXSpeed(100, 200);
    emitterLeft.setYSpeed(-50, 50);
    emitterLeft.makeParticles('ball1', 0, 250, 1, true);
    emitterRight = g.add.emitter(g.world.width - 50, g.world.centerY - 200);
    emitterRight.bounce.setTo(0.5, 0.5);
    emitterRight.setXSpeed(-100, -200);
    emitterRight.setYSpeed(-50, 50);
    emitterRight.makeParticles('ball2', 0, 250, 1, true);
    emitterLeft.start(false, 5000, 20);
    emitterRight.start(false, 5000, 20);
  };
  gUpdate = function(){
    g.physics.collide(emitterLeft, emitterRight);
  };
  gRender = function(){};
  g = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
