// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, music, alien, changeVolume;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update,
    render: render
  });
  function preload(){
    game.load.image('alien', '../../../phaser/examples/assets/ra_dont_crack_under_pressure.png');
    return game.load.audio('boden', ['../../../phaser/examples/assets/bodenstaendig_2000_in_rock_4bit.mp3', '../../../phaser/examples/assets/bodenstaendig_2000_in_rock_4bit.ogg']);
  }
  function create(){
    game.stage.backgroundColor = 'hsl(210,50%,25%)';
    game.input.touch.preventDefault = false;
    music = game.add.audio('boden', 1, true);
    music.play('', 0, 1, true);
    alien = game.add.sprite(game.world.centerX, game.world.centerY, 'alien');
    alien.anchor.setTo(0.5, 0.5);
    return game.input.onDown.add(changeVolume, this);
  }
  changeVolume = function(pointer){
    if (pointer.y < 300) {
      music.pause();
      return console.log("Mouse at " + pointer.y + " (less than 300). Music paused.");
    } else {
      music.resume();
      return console.log("Mouse at " + pointer.y + " (more than 300). Music resumed.");
    }
  };
  function update(){
    return alien.rotation += 0.01;
  }
  function render(){
    return game.debug.renderSoundInfo(music, 20, 32);
  }
}).call(this);
