// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, text, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.bitmapFont('desyrel', assets + 'fonts/desyrel.png', assets + 'fonts/desyrel.xml');
  };
  gCreate = function(){
    g.stage.backgroundColor = '#0072bc';
    text = g.add.bitmapText(200, 100, 'Bitmap Fonts!', {
      font: '64px Desyrel',
      align: 'center'
    });
  };
  gUpdate = function(){
    text.setText('Bitmap Fonts!\nx: ' + Math.round(g.input.x) + ' y: ' + Math.round(g.input.y));
  };
  gRender = function(){};
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
