// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, floor;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    create: create,
    update: update,
    render: render
  });
  function create(){
    return floor = new Phaser.Rectangle(0, 550, 800, 50);
  }
  function render(){
    return game.debug.renderRectangle(floor, '#0fffff');
  }
}).call(this);
