// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, bot;
  game = new Phaser.Game(1200, 768, Phaser.AUTO, '', {
    preload: preload,
    create: create,
    update: update
  });
  function preload(){
    return game.load.atlasJSONHash('bot', '../../../phaser/examples/assets/running_bot.png', '../../../phaser/examples/assets/running_bot.json');
  }
  function create(){
    bot = game.add.sprite(200, 200, 'bot');
    bot.animations.add('run');
    return bot.animations.play('run', 15, true);
  }
  function update(){
    bot.body.velocity.x = -600;
    if (bot.x < -bot.width) {
      bot.x = game.world.width;
      return bot.y = Math.floor(Math.random() * game.world.height);
    }
  }
}).call(this);
