// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, sprite1, sprite2, gPreload, gCreate, gUpdate, gRender, collisionCallback, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.image('atari', assets + 'sprites/atari130xe.png');
    g.load.image('mushroom', assets + 'sprites/mushroom2.png');
  };
  gCreate = function(){
    g.stage.backgroundColor = '#2d2d2d';
    sprite1 = g.add.sprite(130, 200, 'atari');
    sprite1.name = 'atari';
    sprite1.rotation = 0.6;
    sprite1.body.polygon.rotate(0.6);
    sprite1.body.immovable = true;
    sprite2 = g.add.sprite(700, 210, 'mushroom');
    sprite2.name = 'mushroom';
    sprite2.body.velocity.x = -100;
  };
  gUpdate = function(){
    g.physics.collide(sprite1, sprite2, collisionCallback, null, this);
  };
  gRender = function(){
    g.debug.renderBodyInfo(sprite1, 32, 32);
    g.debug.renderPhysicsBody(sprite1.body);
    g.debug.renderPhysicsBody(sprite2.body);
  };
  collisionCallback = function(obj1, obj2){
    return g.stage.backgroundColor = '#992d2d';
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
