// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, emitter, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.image('alien', assets + 'sprites/space-baddie.png');
  };
  gCreate = function(){
    g.stage.backgroundColor = '#337799';
    emitter = g.add.emitter(g.world.centerX, g.world.centerY, 250);
    emitter.makeParticles('alien');
    emitter.minParticleSpeed.setTo(-300, -300);
    emitter.maxParticleSpeed.setTo(300, 300);
    emitter.minRotation = 0;
    emitter.maxRotation = 0;
    emitter.start(false, 4000, 15);
  };
  gUpdate = function(){};
  gRender = function(){};
  g = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
