// Generated by LiveScript 1.2.0
(function(){
  var centerX, rndRange;
  centerX = function(object){
    return Math.floor(game.world.centerX - object.width / 2);
  };
  rndRange = function(min, max){
    var random, range;
    random = Math.floor(Math.random() * (max - min));
    return range = min + random;
  };
}).call(this);
