// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, group1, group2, coke, disk;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update,
    render: render
  });
  function preload(){
    game.load.image('beast', '../../../phaser/examples/assets/pics/shadow_of_the_beast2_karamoon.png');
    game.load.image('snot', '../../../phaser/examples/assets/pics/nslide_snot.png');
    game.load.image('atari1', '../../../phaser/examples/assets/sprites/atari130xe.png');
    game.load.image('sonic', '../../../phaser/examples/assets/sprites/sonic_havok_sanity.png');
    game.load.image('coke', '../../../phaser/examples/assets/sprites/cokecan.png');
    return game.load.image('disk', '../../../phaser/examples/assets/sprites/oz_pov_melting_disk.png');
  }
  function create(){
    var bg, i$, i, tmp, snot;
    bg = game.add.sprite(0, 0, 'beast');
    bg.scale.setTo(1.5, 1.5);
    group1 = game.add.group();
    group2 = game.add.group();
    for (i$ = 0; i$ < 10; ++i$) {
      i = i$;
      tmp = game.add.sprite(game.world.randomX, game.world.randomY, 'atari1');
      tmp.name = 'atari' + i;
      tmp.input.start(i, true);
      tmp.input.enableDrag(false, true);
      group1.add(tmp);
      tmp = game.add.sprite(game.world.randomX, game.world.randomY, 'sonic');
      tmp.name = 'sonic' + i;
      tmp.input.start(10 + i, true);
      tmp.input.enableDrag(false, true);
      group2.add(tmp);
    }
    coke = group1.create(100, 100, 'coke');
    disk = group2.create(400, 300, 'disk');
    snot = game.add.sprite(game.world.centerX, game.world.height, 'snot');
    return snot.anchor.setTo(0.5, 1);
  }
  function update(){
    if (game.input.keyboard.justReleased(Phaser.Keyboard.ONE)) {
      coke.bringToTop();
      console.log('coke.bring-to-top!');
    }
    if (game.input.keyboard.justReleased(Phaser.Keyboard.TWO)) {
      disk.bringToTop();
      return console.log('disk.bring-to-top!');
    }
  }
  function render(){
    return game.debug.renderInputInfo(32, 32);
  }
}).call(this);
