// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var map, timer, delay, preload, create, update, render, createSprites, createSprite, timerExtend, killOldest, g;
  map = require('prelude-ls').map;
  timer = 1000;
  delay = 1000;
  preload = function(){
    g.load.spritesheet('item', 'assets/buttons/number-buttons-90x90.png', 90, 90);
    return g.load.image('revive-btn', 'assets/buttons/revive-button.png');
  };
  create = function(){
    return map(createSprites, [0, 1, 2]);
  };
  update = function(){
    if (g.time.now > timer) {
      timerExtend(delay);
      return killOldest();
    }
  };
  render = function(){
    g.debug.renderText('One of the items will be killed each second', 280, 420);
    return g.debug.renderText("Living: " + g.world.countLiving() + " Dead: " + g.world.countDead(), 330, 440);
  };
  createSprites = function(i){
    createSprite(i, 0);
    return createSprite(i, 3);
  };
  createSprite = function(i, displacement){
    var s;
    return s = g.add.sprite(290 + 33 * displacement, 98 * (i + 1), 'item', i + displacement);
  };
  timerExtend = function(delay){
    return timer = g.time.now + delay;
  };
  killOldest = function(){
    var item;
    item = g.world.getFirstAlive();
    if (item) {
      return item.kill();
    }
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update,
    render: render
  });
}).call(this);
