// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, gofull;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update,
    render: render
  });
  function preload(){
    return game.load.image('atari', 'assets/sprites/atari130xe.png');
  }
  function create(){
    var sprite;
    sprite = game.add.sprite(0, 0, 'atari');
    game.stage.backgroundColor = '#e3ed49';
    return game.input.onDown.add(gofull, this);
  }
  gofull = function(){
    return game.stage.scale.startFullScreen();
  };
  function update(){
    if (document.getElementsByTagName('body')[0].scrollTop > 1000) {
      game.stage.backgroundColor = '#87ff55';
      return window.scrollTo(0, 0);
    }
  }
  function render(){
    return game.debug.renderText('Tap to go fullscreen', 32, 150);
  }
}).call(this);
