// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, bg, filter;
  game = new Phaser.Game(800, 600, Phaser.WEBGL, '', {
    preload: preload,
    create: create,
    update: update
  });
  function preload(){
    game.load.image('phaser', '../../../phaser/examples/assets/sprites/phaser2.png');
    return game.load.script('filter', 'filters/LightBeam.js');
  }
  function create(){
    var logo;
    logo = game.add.sprite(game.world.centerX, game.world.centerY, 'phaser');
    logo.anchor.setTo(0.5, 0.5);
    bg = game.add.sprite(0, 0);
    bg.width = 800;
    bg.height = 600;
    filter = game.add.filter('LightBeam', 800, 600);
    filter.alpha = 0.0;
    return bg.filters = [filter];
  }
  function update(){
    return filter.update();
  }
}).call(this);
