// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var map, firstGroup, preload, create, render, createSprite, logGroupAdd, g;
  map = require('prelude-ls').map;
  preload = function(){
    return g.load.image('sonic', 'assets/sprites/sonic_havok_sanity.png');
  };
  create = function(){
    firstGroup = g.add.group();
    firstGroup.name = 'JOYEE';
    return map(createSprite, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
  };
  render = function(){
    return g.debug.renderText('Tap or click an item to kill it, and press the revive button to revive them all', 80, 500);
  };
  createSprite = function(i){
    var s;
    s = g.add.sprite(g.world.randomX, g.world.randomY, 'sonic');
    s.events.onAddedToGroup.add(logGroupAdd);
    return firstGroup.add(s);
  };
  logGroupAdd = function(sprite, group){
    return console.log('Sprite added to Group', group.name, 'at z-index:', group.getIndex(sprite));
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    render: render
  });
}).call(this);
