// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, centerX;
  game = new Phaser.Game(800, 768, Phaser.AUTO, '', {
    create: create
  });
  function create(){
    var text1, text2, h1, h2, paddingTop, textGroup, tes3, morrowind;
    text1 = "The Elder Scrolls III";
    text2 = "Morrowind";
    h1 = {
      font: "128px Times",
      fontWeight: "bold",
      fill: "hsl(35,50%,90%)",
      stroke: "hsl(25,60%,45%)",
      strokeThickness: "5"
    };
    h2 = {
      font: "64px Times",
      fill: "hsl(35,50%,90%)",
      background: "red"
    };
    paddingTop = 256;
    textGroup = game.add.group();
    tes3 = game.add.text(0, paddingTop, text1, h2);
    tes3.x = centerX(tes3);
    textGroup.add(tes3);
    morrowind = game.add.text(0, tes3.height + paddingTop, text2, h1);
    morrowind.x = centerX(morrowind);
    textGroup.add(tes3);
    return textGroup.add(morrowind);
  }
  centerX = function(object){
    return Math.floor(game.world.centerX - object.width / 2);
  };
}).call(this);
