// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, circle;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    create: create,
    render: render
  });
  function create(){
    return circle = new Phaser.Circle(game.world.centerX, 100, 64);
  }
  function render(){
    game.debug.renderCircle(circle, '#cfffff');
    game.debug.renderText("Diameter: " + circle.diameter, 50, 200);
    return game.debug.renderText("Circumference: " + circle.circumference(), 50, 230);
  }
}).call(this);
