// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, bot, changeMummy;
  game = new Phaser.Game(1200, 768, Phaser.AUTO, '', {
    preload: preload,
    create: create,
    render: render
  });
  function preload(){
    game.load.atlasJSONHash('bot', '../../../phaser/examples/assets/sprites/running_bot.png', '../../../phaser/examples/assets/sprites/running_bot.json');
    return game.load.spritesheet('mummy', '../../../phaser/examples/assets/sprites/metalslug_mummy37x45.png', 37, 45, 18);
  }
  function create(){
    bot = game.add.sprite(200, 200, 'bot');
    bot.animations.add('run');
    bot.animations.play('run', 15, true);
    return game.input.onDown.addOnce(changeMummy, this);
  }
  changeMummy = function(){
    bot.loadTexture('mummy', 0);
    bot.animations.add('walk');
    return bot.animations.play('walk', 30, true);
  };
  function render(){
    return game.debug.renderSpriteBounds(bot);
  }
}).call(this);
