// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var b, gPreload, gCreate, gUpdate, gRender, spriteOver, spriteOut, g;
  gPreload = function(){
    g.load.image('img-bunny', 'assets/sprites/bunny.png');
  };
  gCreate = function(){
    b = g.add.sprite(g.world.centerX, g.world.centerY, 'img-bunny');
    b.anchor.setTo(0.5, 0.5);
    b.inputEnabled = true;
    b.input.pixelPerfect = true;
    b.input.useHandCursor = true;
    b.events.onInputOver.add(spriteOver, this);
    b.events.onInputOut.add(spriteOut, this);
  };
  gUpdate = function(){
    b.angle += 0.05;
  };
  gRender = function(){
    g.debug.renderSpriteInputInfo(b, 32, 32);
    g.debug.renderSpriteCorners(b);
    g.debug.renderPoint(b.input._tempPoint);
  };
  spriteOver = function(){
    return console.log('over');
  };
  spriteOut = function(){
    return console.log('out');
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
