// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, filters, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  filters = '../../../phaser/filters/';
  gPreload = function(){
    g.load.image('phaser', assets + 'sprites/phaser2.png');
    g.load.script('filterX', filters + 'BlurX.js');
    g.load.script('filterY', filters + 'BlurY.js');
  };
  gCreate = function(){
    var logo, blurX, blurY;
    logo = g.add.sprite(g.world.centerX, g.world.centerY, 'phaser');
    logo.anchor.setTo(0.5, 0.5);
    blurX = g.add.filter('BlurX');
    blurY = g.add.filter('BlurY');
    logo.filters = [blurX, blurY];
  };
  gUpdate = function(){};
  gRender = function(){};
  g = new Phaser.Game(800, 600, Phaser.WEBGL, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
