// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game;
  game = new Phaser.Game(800, 600, Phaser.WEBGL, '', {
    preload: preload,
    create: create
  });
  function preload(){
    game.load.image('phaser', '../../../phaser/examples/assets/sprites/phaser2.png');
    game.load.script('filterX', 'filters/BlurX.js');
    return game.load.script('filterY', 'filters/BlurY.js');
  }
  function create(){
    var logo, blurX, blurY;
    logo = game.add.sprite(game.world.centerX, game.world.centerY, 'phaser');
    logo.anchor.setTo(0.5, 0.5);
    blurX = game.add.filter('BlurX');
    blurY = game.add.filter('BlurY');
    return logo.filters = [blurX, blurY];
  }
}).call(this);
