// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var map, enemies, preload, create, killBaddie, killIt, createBaddie, g;
  map = require('prelude-ls').map;
  preload = function(){
    g.load.image('baddie', 'assets/sprites/space-baddie.png');
    return g.load.spritesheet('button', 'assets/buttons/baddie-buttons.png', 224, 70);
  };
  create = function(){
    var i$, i, x, y;
    enemies = g.add.group();
    for (i$ = 0; i$ < 8; ++i$) {
      i = i$;
      x = 360 + Math.floor(Math.random() * 200);
      y = 120 + Math.floor(Math.random() * 200);
      enemies.create(x, y, 'baddie');
    }
    g.add.button(16, 50, 'button', createBaddie, this, 0, 0, 0);
    return g.add.button(16, 130, 'button', killBaddie, this, 1, 1, 1);
  };
  killBaddie = function(){
    var baddie, tween;
    baddie = enemies.getFirstAlive();
    if (baddie) {
      tween = g.add.tween(baddie).to({
        y: baddie.y + 50,
        alpha: 0.5
      }, 250, Phaser.Easing.Elastic.Out, true, 0, 0, true);
      return tween.onComplete.add(killIt, this);
    }
  };
  killIt = function(sprite){
    return sprite.kill();
  };
  createBaddie = function(){
    var enemy;
    enemy = enemies.getFirstExists(false);
    if (enemy) {
      enemy.revive();
      return g.add.tween(enemy).to({
        y: enemy.y - 50,
        alpha: 1
      }, 250, Phaser.Easing.Elastic.Out, true, 0, 0, true);
    }
  };
  g = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: preload,
    create: create
  });
}).call(this);
