// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, rect, circle, point, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  rect = new Phaser.Rectangle(100, 100, 100, 100);
  circle = new Phaser.Circle(280, 150, 100);
  point = new Phaser.Point(100, 280);
  gPreload = function(){};
  gCreate = function(){};
  gUpdate = function(){};
  gRender = function(){
    g.debug.renderRectangle(rect, '#ff0000');
    g.debug.renderCircle(circle, '#ffff00');
    g.debug.renderPoint(point, '#ffffff');
    g.debug.renderPixel(200, 280, '#00ffff');
    g.debug.renderText("This is debug text", 100, 380);
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
