// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, jellyfish, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.atlasXML('seacreatures', assets + 'sprites/seacreatures.png', assets + 'sprites/seacreatures.xml');
    g.load.image('undersea', assets + 'pics/undersea.jpg');
    g.load.image('coral', assets + 'pics/seabed.png');
  };
  gCreate = function(){
    g.add.sprite(0, 0, 'undersea');
    jellyfish = g.add.sprite(330, 100, 'seacreatures');
    jellyfish.animations.add('swim', Phaser.Animation.generateFrameNames('greenJellyfish', 0, 39, '', 4), 30, true);
    jellyfish.animations.play('swim');
    g.add.sprite(0, 466, 'coral');
    g.add.tween(jellyfish).to({
      y: 250
    }, 4000, Phaser.Easing.Quadratic.InOut(true, 0, 10000, true));
  };
  gUpdate = function(){};
  gRender = function(){};
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
