// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game;
  game = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: preload,
    create: create
  });
  function preload(){
    game.load.image('spyro', 'assets/spyro.png');
    return game.load.audio('squirt', ['assets/squit.mp3', 'assetssquit.ogg']);
  }
  function create(){
    var music, s;
    game.stage.backgroundColor = 'hsl(25,50%,95%)';
    music = game.add.audio('squirt', 1, true);
    music.play('', 0, 1, true);
    s = game.add.sprite(game.world.centerX, game.world.centerY, 'spyro');
    return s.anchor.setTo(0.5, 0.5);
  }
}).call(this);
