// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, image;
  game = new Phaser.Game(1200, 768, Phaser.AUTO, '', {
    preload: preload,
    create: create,
    update: update,
    render: render
  });
  function preload(){
    game.load.image('bird', '../../../phaser/examples/assets/bird.png');
    return game.load.image('sky', '../../../phaser/examples/assets/sky.png');
  }
  function create(){
    game.add.sprite(0, 0, 'sky');
    return image = game.add.sprite(0, 0, 'bird');
  }
  function update(){
    return game.physics.moveToPointer(image, 300, game.input.activePointer);
  }
  function render(){
    return game.debug.renderInputInfo(32, 32);
  }
}).call(this);
