// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, sprite1, sprite2, gPreload, gCreate, gUpdate, gRender, collisionCallback, processCallback, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.image('atari', assets + 'sprites/atari130xe.png');
    g.load.image('mushroom', assets + 'sprites/mushroom2.png');
  };
  gCreate = function(){
    g.stage.backgroundColor = '#2d2d2d';
    sprite1 = g.add.sprite(0, 200, 'atari');
    sprite1.body.velocity.x = 50 + Math.random() * 100;
    sprite2 = g.add.sprite(750, 220, 'mushroom');
    sprite2.body.velocity.x = -(50 + Math.random() * 100);
  };
  gUpdate = function(){
    g.physics.collide(sprite1, sprite2, collisionCallback, processCallback, this);
  };
  gRender = function(){
    g.debug.renderText('The process-handler will only collide if sprite1 is fastest', 32, 32);
    g.debug.renderText("sprite1 speed " + sprite1.body.speed, 32, 64);
    g.debug.renderText("sprite2 speed " + sprite2.body.speed, 32, 96);
  };
  collisionCallback = function(obj1, obj2){
    return g.stage.backgroundColor = '#992d2d';
  };
  processCallback = function(obj1, obj2){
    if (obj1.body.speed > obj2.body.speed) {
      return true;
    } else {
      return false;
    }
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
