// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var map, sprite, gamePreload, gameCreate, gameUpdate, game;
  map = require('prelude-ls').map;
  gamePreload = function(){
    return game.load.image('image-ball', 'assets/sprites/shinyball.png');
  };
  gameCreate = function(){
    return sprite = game.add.sprite(game.world.centerX, game.world.centerY, 'image-ball');
  };
  gameUpdate = function(){
    if (game.input.mousePointer.isDown) {
      game.physics.moveToPointer(sprite, 400);
      if (Phaser.Rectangle.contains(sprite.body, game.input.x, game.input.y)) {
        return sprite.body.velocity.setTo(0, 0);
      }
    } else {
      return sprite.body.velocity.setTo(0, 0);
    }
  };
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gamePreload,
    create: gameCreate,
    update: gameUpdate
  });
}).call(this);
