// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, sprite, otherSprite, counter, step, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  counter = 0;
  step = Math.PI * 2 / 360;
  gPreload = function(){
    g.load.image('sprite', assets + 'sprites/phaser2.png');
    g.load.image('other-sprite', assets + 'sprites/phaser-dude.png');
  };
  gCreate = function(){
    sprite = g.add.sprite(0, 0, 'sprite');
    sprite.alpha = 0.5;
    sprite.x = g.width / 2;
    sprite.anchor.setTo(0.5, 0.5);
    otherSprite = g.add.sprite(0, 0, 'other-sprite');
    otherSprite.alpha = 0.5;
    otherSprite.x = g.width / 2 + 150;
    otherSprite.y = g.width / 2 + 150;
    otherSprite.anchor.setTo(0.5, 0.5);
    otherSprite.body.immovable = true;
  };
  gUpdate = function(){
    var tStep;
    g.physics.collide(sprite, otherSprite);
    tStep = Math.sin(counter);
    sprite.y = g.height / 2 + tStep * 30;
    sprite.rotation += Phaser.Math.degToRad(0.1 * tStep);
    counter += step;
  };
  gRender = function(){
    g.debug.renderSpriteBody(sprite);
    g.debug.renderSpriteCollision(sprite, 32, 32);
    g.debug.renderSpriteBody(otherSprite);
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
