// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var sprite1, sprite2, sprite3, sprite4, assets, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.image('parsec', assets + 'sprites/parsec.png');
    g.load.image('wizball', assets + 'sprites/wizball.png');
    g.load.image('spaceman', assets + 'sprites/exocet_spaceman.png');
  };
  gCreate = function(){
    g.stage.backgroundColor = '#2d2d2d';
    g.physics.gravity.y = 100;
    sprite1 = g.add.sprite(80, 200);
    sprite1.body.setPolygon(0, 0, 60, 0, 100, 40, 60, 80, 0, 80);
    sprite1.body.translate(0, 144);
    sprite1.body.immovable = true;
    sprite1.body.allowGravity = false;
    sprite2 = g.add.sprite(450, 300, 'parsec');
    sprite2.body.setPolygon(56, -1, 10, -5, 1, -13, 0, -34, 55, -60, 112, -78, 165, -80, 214, -74, 285, -71, 296, -44, 298, -12, 292, -5, 168, -3);
    sprite2.body.translate(0, 80);
    sprite2.body.immovable = true;
    sprite2.body.allowGravity = false;
    sprite3 = g.add.sprite(230, 400, 'spaceman');
    sprite3.body.setPolygon(34, -172, 75, -172, 87, -145, 121, -52, 105, -16, 55, -3, 9, -19, 1, -57, 24, -145);
    sprite3.body.translate(0, 175);
    sprite3.body.immovable = true;
    sprite3.body.allowGravity = false;
    sprite4 = g.add.sprite(380, 100, 'wizball');
    sprite4.body.setCircle(46);
    sprite4.body.collideWorldBounds = true;
    sprite4.body.friction = 0;
    sprite4.body.bounce.setTo(0.9, 0.9);
    sprite4.body.velocity.setTo(100, 100);
  };
  gUpdate = function(){
    g.physics.collideArray(sprite4, [sprite1, sprite2, sprite3]);
  };
  gRender = function(){
    g.debug.renderBodyInfo(sprite4, 32, 32);
    g.debug.renderPhysicsBody(sprite1.body);
    g.debug.renderPhysicsBody(sprite2.body);
    g.debug.renderPhysicsBody(sprite3.body);
    g.debug.renderPhysicsBody(sprite4.body);
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
