// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var sprite1, sprite2, sprite3, assets, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.spritesheet('gameboy', assets + 'sprites/gameboy_seize_color_40x60.png', 40, 60);
    g.load.image('atari', assets + 'sprites/atari130xe.png');
  };
  gCreate = function(){
    g.stage.backgroundColor = '#124184';
    sprite1 = g.add.sprite(300, 200, 'atari');
    sprite1.name = 'atari';
    sprite1.body.collideWorldBounds = true;
    sprite1.body.checkCollision.up = false;
    sprite1.body.checkCollision.down = false;
    sprite1.body.immovable = true;
    sprite2 = g.add.sprite(350, 400, 'gameboy', 2);
    sprite2.name = 'gameboy1';
    sprite2.body.collideWorldBounds = true;
    sprite2.body.bounce.setTo(1, 1);
    sprite3 = g.add.sprite(1, 210, 'gameboy', 4);
    sprite3.name = 'gameboy2';
    sprite3.body.collideWorldBounds = true;
    sprite3.body.bounce.setTo(1, 1);
    sprite2.body.velocity.y = -200;
    sprite3.body.velocity.x = 200;
  };
  gUpdate = function(){
    g.physics.collide(sprite1, sprite2);
    g.physics.collide(sprite1, sprite3);
  };
  gRender = function(){
    g.debug.renderPhysicsBody(sprite1.body);
    g.debug.renderPhysicsBody(sprite2.body);
    g.debug.renderPhysicsBody(sprite3.body);
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
