// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, alien, cursors;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update,
    render: render
  });
  function preload(){
    return game.load.image('alien', '../../../phaser/examples/assets/sprites/ra_dont_crack_under_pressure.png');
  }
  function create(){
    game.stage.backgroundColor = 'hsl(210,50%,25%)';
    alien = game.add.sprite(game.world.centerX, game.world.centerY, 'alien');
    alien.anchor.setTo(0.5, 0.5);
    game.input.onDown[console.log("clicked this board")];
    return cursors = game.input.keyboard.createCursorKeys();
  }
  function update(){
    alien.rotation += 0.01;
    if (cursors.up.isDown) {
      alien.y -= 4;
    } else if (cursors.down.isDown) {
      alien.y += 4;
    }
    if (cursors.left.isDown) {
      return alien.x -= 4;
    } else if (cursors.right.isDown) {
      return alien.x += 4;
    }
  }
  function render(){
    game.debug.renderSpriteCorners(alien, true, true);
    return game.debug.renderSpriteInfo(alien, 20, 32);
  }
}).call(this);
