// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game;
  game = new Phaser.Game(800, 600, Phaser.WEBGL, '', {
    create: create
  });
  function create(){
    var g;
    g = game.add.graphics(50, 50);
    g.beginFill(0xff0000);
    g.lineStyle(10, 0xff0000, 1);
    g.moveTo(50, 50);
    g.lineTo(250, 50);
    return g.endFill();
  }
}).call(this);
