// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, sprite1, sprite2, collisionHandler;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update,
    render: render
  });
  function preload(){
    game.load.image('atari', 'assets/atari130xe.png');
    return game.load.image('mushroom', 'assets/mushroom2.png');
  }
  function create(){
    game.stage.backgroundColor = '#2d2d2d';
    sprite1 = game.add.sprite(150, 300, 'atari');
    sprite1.name = 'atari';
    sprite1.body.immovable = true;
    sprite2 = game.add.sprite(700, 320, 'mushroom');
    sprite2.name = 'mushroom';
    return sprite2.body.velocity.x = -100;
  }
  function update(){
    return game.physics.collide(sprite1, sprite2, collisionHandler, null, this);
  }
  collisionHandler = function(obj1, obj2){
    return game.stage.backgroundColor = '#992d2d';
  };
  function render(){
    game.debug.renderSpriteInfo(sprite1, 32, 32);
    game.debug.renderPhysicsBody(sprite1.body);
    return game.debug.renderPhysicsBody(sprite2.body);
  }
}).call(this);
