// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, octopus, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.atlas('seacreatures', assets + 'sprites/seacreatures_json.png', assets + 'sprites/seacreatures_json.json');
    g.load.image('undersea', assets + 'pics/undersea.jpg');
    g.load.image('coral', assets + 'pics/seabed.png');
  };
  gCreate = function(){
    g.add.sprite(0, 0, 'undersea');
    octopus = g.add.sprite(330, 100, 'seacreatures');
    octopus.animations.add('swim', Phaser.Animation.generateFrameNames('octopus', 0, 24, '', 4), 30, true);
    octopus.animations.play('swim');
    g.add.tween(octopus).to({
      y: 250
    }, 4000, Phaser.Easing.Quadratic.InOut, true, 0, 10000, true);
    g.add.sprite(0, 466, 'coral');
  };
  gUpdate = function(){};
  gRender = function(){
    var i$, i;
    for (i$ = 0; i$ < 30; ++i$) {
      i = i$;
      g.debug.renderText(text[i], 32, i * 20);
    }
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
