// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, sprite1, sprite2, processHandler, collisionHandler;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update
  });
  function preload(){
    game.load.image('atari', '../../../phaser/examples/assets/sprites/atari130xe.png');
    return game.load.image('mushroom', '../../../phaser/examples/assets/sprites/mushroom2.png');
  }
  function create(){
    game.stage.backgroundColor = '#2d2d2d';
    sprite1 = game.add.sprite(0, 200, 'atari');
    sprite1.name = 'atari';
    sprite1.body.velocity.x = 50 + Math.random() * 100;
    sprite1.body.customSeparateX = true;
    sprite2 = game.add.sprite(750, 220, 'mushroom');
    sprite2.name = 'mushroom';
    sprite2.body.velocity.x = -(50 + Math.random() * 100);
    return sprite2.body.customSeparateX = true;
  }
  function update(){
    return game.physics.collide(sprite1, sprite2, collisionHandler, processHandler, this);
  }
  processHandler = function(obj1, obj2){
    if (obj1.body.velocity.x > Math.abs(obj2.body.velocity.x)) {
      obj2.kill();
      obj1.body.velocity.x = 0;
    } else {
      obj1.kill();
      obj2.body.velocity.x = 0;
    }
    return true;
  };
  collisionHandler = function(obj1, obj2){
    game.stage.backgroundColor = '#992d2d';
    return console.log(obj1.name + " collided with " + obj2.name);
  };
}).call(this);
