// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var map, robot, preload, create, update, g;
  map = require('prelude-ls').map;
  preload = function(){
    g.load.image('eye', '../../../phaser/examples/assets/sprites/robot/eye.png');
    g.load.image('body', '../../../phaser/examples/assets/sprites/robot/body.png');
    g.load.image('arm-l', '../../../phaser/examples/assets/sprites/robot/arm-l.png');
    g.load.image('arm-r', '../../../phaser/examples/assets/sprites/robot/arm-r.png');
    g.load.image('leg-l', '../../../phaser/examples/assets/sprites/robot/leg-l.png');
    return g.load.image('leg-r', '../../../phaser/examples/assets/sprites/robot/leg-r.png');
  };
  create = function(){
    var gcx, gcy, offsetX, offsetY;
    gcx = g.world.centerX;
    gcy = g.world.centerY;
    offsetX = -g.world.width / 2;
    offsetY = -g.world.height / 2;
    robot = g.add.group();
    robot.x = gcx;
    robot.y = gcy;
    robot.create(offsetX + 90, offsetY + 175, 'arm-l');
    robot.create(offsetX + 549, offsetY + 175, 'arm-r');
    robot.create(offsetX + 270, offsetY + 325, 'leg-l');
    robot.create(offsetX + 410, offsetY + 325, 'leg-r');
    robot.create(offsetX + 219, offsetY + 32, 'body');
    return robot.create(offsetX + 335, offsetY + 173, 'eye');
  };
  update = function(){
    return robot.angle += 2;
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update
  });
}).call(this);
