// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game;
  game = new Phaser.Game(800, 768, Phaser.AUTO, '', {
    preload: preload,
    create: create
  });
  function preload(){
    return game.load.atlasJSONHash('bot', '../../../phaser/examples/assets/sprites/running_bot.png', '../../../phaser/examples/assets/sprites/running_bot.json');
  }
  function create(){
    var dude;
    dude = game.add.sprite(200, 200, 'bot');
    dude.animations.add('run');
    return dude.animations.play('run', 15, true);
  }
}).call(this);
