// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game;
  game = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: preload,
    create: create
  });
  function preload(){
    return game.load.spritesheet('mummy', '../../../phaser/examples/assets/metalslug_mummy37x45.png', 37, 45, 18);
  }
  function create(){
    var mummy;
    mummy = game.add.sprite(300, 200, 'mummy');
    mummy.animations.add('walk');
    return mummy.animations.play('walk', 20, true);
  }
}).call(this);
