// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, ufo, keys, speed, style, lockonFollow, platformerFollow, topdownFollow, topdownTightFollow;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update,
    render: render
  });
  keys = Phaser.Keyboard;
  speed = 4;
  style = 'default';
  function preload(){
    game.load.image('ground', 'assets/ground-2x.png');
    game.load.image('river', 'assets/river-2x.png');
    game.load.image('sky', 'assets/sky-2x.png');
    game.load.image('cloud0', 'assets/cloud-big-2x.png');
    game.load.image('cloud1', 'assets/cloud-narrow-2x.png');
    game.load.image('cloud2', 'assets/cloud-small-2x.png');
    game.load.image('ufo', 'assets/ufo.png');
    game.load.image('baddie', 'assets/space-baddie.png');
    return game.load.spritesheet('button', 'assets/follow-style-button.png', 224, 70);
  }
  function create(){
    var i$, i, btn0, btn1, btn2, btn3;
    game.world.setBounds(0, 0, 1400, 1400);
    for (i$ = 0; i$ < 10; ++i$) {
      i = i$;
      game.add.sprite(game.world.randomX, game.world.randomY, 'baddie');
    }
    game.add.tileSprite(0, 0, 1400, 600, 'sky');
    game.add.sprite(0, 360, 'ground');
    game.add.sprite(0, 400, 'river');
    game.add.sprite(200, 120, 'cloud0');
    game.add.sprite(-60, 120, 'cloud1');
    game.add.sprite(900, 170, 'cloud2');
    ufo = game.add.sprite(300, 240, 'ufo');
    ufo.anchor.setTo(0.5, 0.5);
    console.log(ufo);
    game.camera.follow(ufo);
    btn0 = game.add.button(6, 40, 'button', lockonFollow, this, 0, 0, 0);
    btn1 = game.add.button(6, 120, 'button', platformerFollow, this, 1, 1, 1);
    btn2 = game.add.button(6, 200, 'button', topdownFollow, this, 2, 2, 2);
    return btn3 = game.add.button(6, 280, 'button', topdownTightFollow, this, 3, 3, 3);
  }
  lockonFollow = function(){
    game.camera.follow(ufo, Phaser.Camera.FOLLOW_LOCKON);
    return style = 'STYLE_LOCKON';
  };
  platformerFollow = function(){
    game.camera.follow(ufo, Phaser.Camera.FOLLOW_PLATFORMER);
    return style = 'STYLE_PLATFORMER';
  };
  topdownFollow = function(){
    game.camera.follow(ufo, Phaser.Camera.FOLLOW_TOPDOWN);
    return style = 'STYLE_TOPDOWN';
  };
  topdownTightFollow = function(){
    game.camera.follow(ufo, Phaser.Camera.FOLLOW_TOPDOWN_TIGHT);
    return style = 'STYLE_TOPDOWN_TIGHT';
  };
  function update(){
    if (game.input.keyboard.isDown(keys.LEFT)) {
      ufo.x -= speed;
      return ufo.angle = -15;
    } else if (game.input.keyboard.isDown(keys.RIGHT)) {
      ufo.x += speed;
      return ufo.angle = 15;
    } else if (game.input.keyboard.isDown(keys.UP)) {
      return ufo.y -= speed;
    } else if (game.input.keyboard.isDown(keys.DOWN)) {
      return ufo.y += speed;
    } else {
      return ufo.angle = 0;
    }
  }
  function render(){
    game.debug.renderText('Click buttons to switch follow styles', 32, 32);
    return game.debug.renderText("Current style: " + style, 32, 64);
  }
}).call(this);
