// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, sprite1, sprite2, collisionHandler;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update,
    render: render
  });
  function preload(){
    game.load.image('atari', '../../../phaser/examples/assets/atari130xe.png');
    return game.load.image('mushroom', '../../../phaser/examples/assets/mushroom2.png');
  }
  function create(){
    game.stage.backgroundColor = '#2d2d2d';
    sprite1 = game.add.sprite(50, 200, 'atari');
    sprite1.name = 'atari';
    sprite1.body.velocity.x = 100;
    sprite1.body.setSize(100, 50, 50, 25);
    sprite2 = game.add.sprite(700, 220, 'mushroom');
    sprite2.name = 'mushroom';
    return sprite2.body.velocity.x = -100;
  }
  function update(){
    return game.physics.collide(sprite1, sprite2, collisionHandler, null, this);
  }
  collisionHandler = function(obj1, obj2){
    game.stage.backgroundColor = '#992d2d';
    return console.log(obj1 + ".name collided with " + obj2 + ".name");
  };
  function render(){
    game.debug.renderRectangle(sprite1.body);
    return game.debug.renderRectangle(sprite2.body);
  }
}).call(this);
