// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var map, items, card, preload, create, removeCard, replaceCard, g;
  map = require('prelude-ls').map;
  preload = function(){
    g.load.image('atari1', '../../../phaser/examples/assets/sprites/atari130xe.png');
    g.load.image('atari2', '../../../phaser/examples/assets/sprites/atari800xl.png');
    return g.load.image('card', '../../../phaser/examples/assets/sprites/mana_card.png');
  };
  create = function(){
    items = g.add.group();
    items.create(64, 100, 'atari1');
    card = items.create(240, 80, 'card');
    items.create(280, 100, 'atari2');
    return g.input.onTap.addOnce(removeCard, this);
  };
  removeCard = function(){
    card.kill();
    return g.input.onTap.addOnce(replaceCard, this);
  };
  replaceCard = function(){
    return function(it){
      return it.revive();
    }(
    items.getFirstDead());
  };
  g = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: preload,
    create: create
  });
}).call(this);
