// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var sprite, keyUp, keyDown, keyLeft, keyRight, gamePreload, gameCreate, gameUpdate, game;
  gamePreload = function(){
    return game.load.image('image-phaser', 'assets/sprites/phaser-dude.png');
  };
  gameCreate = function(){
    game.stage.backgroundColor = '#736357';
    sprite = game.add.sprite(300, 300, 'image-phaser');
    keyUp = game.input.keyboard.addKey(Phaser.Keyboard.UP);
    keyDown = game.input.keyboard.addKey(Phaser.Keyboard.DOWN);
    keyLeft = game.input.keyboard.addKey(Phaser.Keyboard.LEFT);
    return keyRight = game.input.keyboard.addKey(Phaser.Keyboard.RIGHT);
  };
  gameUpdate = function(){
    if (keyLeft.isDown) {
      sprite.x -= 4;
    } else if (keyRight.isDown) {
      sprite.x += 4;
    }
    if (keyUp.isDown) {
      return sprite.y -= 4;
    } else if (keyDown.isDown) {
      return sprite.y += 4;
    }
  };
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gamePreload,
    create: gameCreate,
    update: gameUpdate
  });
}).call(this);
