// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, star, texture1, texture2, texture3, stars, stageTtl, stageOne, stageTwo;
  game = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: preload,
    create: create,
    update: update
  });
  function preload(){
    return game.load.image('star', 'assets/sprites/bullet.png');
  }
  stars = [];
  stageTtl = 200;
  stageOne = Math.floor(stageTtl * 1 / 3);
  stageTwo = Math.floor(stageTtl * 2 / 3);
  function create(){
    var t, s, i$, to$, i, results$ = [];
    star = game.add.sprite(0, 0, 'star');
    star.visible = false;
    texture1 = game.add.renderTexture('texture1', 800, 600);
    texture2 = game.add.renderTexture('texture2', 800, 600);
    texture3 = game.add.renderTexture('texture3', 800, 600);
    game.add.sprite(0, 0, texture1);
    game.add.sprite(0, 0, texture2);
    game.add.sprite(0, 0, texture3);
    t = texture1;
    s = 4;
    for (i$ = 0, to$ = stageTtl; i$ < to$; ++i$) {
      i = i$;
      if (i === stageOne) {
        s = 6;
        t = texture2;
      } else if (i === stageTwo) {
        s = 10;
        t = texture3;
      }
      results$.push(stars.push({
        x: game.world.randomX,
        y: game.world.randomY,
        speed: s,
        texture: t
      }));
    }
    return results$;
  }
  function update(){
    var i$, to$, i, results$ = [];
    for (i$ = 0, to$ = stageTtl; i$ < to$; ++i$) {
      i = i$;
      stars[i].y += stars[i].speed;
      if (stars[i].y > 600) {
        stars[i].x = game.world.randomX;
        stars[i].y = -32;
      }
      if (i === 0 || i === stageOne || i === stageTwo) {
        results$.push(stars[i].texture.renderXY(star, stars[i].x, stars[i].y, true));
      } else {
        results$.push(stars[i].texture.renderXY(star, stars[i].x, stars[i].y, false));
      }
    }
    return results$;
  }
}).call(this);
