// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var g, background, button, onClick;
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update
  });
  function preload(){
    g.load.spritesheet('button', '../../../phaser/examples/assets/buttons/button_sprite_sheet.png', 193, 71);
    return g.load.image('background', '../../../phaser/examples/assets/misc/starfield.jpg');
  }
  function create(){
    g.add.tileSprite(0, 0, 800, 600, 'background');
    button = g.add.button(g.world.centerX, g.world.centerY, 'button', onClick, this, 2, 1, 0);
    return button.anchor.setTo(0.5, 0.5);
  }
  function update(){
    return button.angle += 1;
  }
  onClick = function(){
    return alert("Though I'm turning around, you can still click on me");
  };
}).call(this);
