// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, background, button, onClick;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update
  });
  function preload(){
    game.load.spritesheet('button', '../../../phaser/examples/assets/button_sprite_sheet.png', 193, 71);
    return game.load.image('background', '../../../phaser/examples/assets/starfield.jpg');
  }
  function create(){
    game.stage.backgroundColor = '#cccccc';
    button = game.add.button(game.world.centerX, game.world.centerY, 'button', onClick, this, 2, 1, 0);
    return button.anchor.setTo(0.5, 0.5);
  }
  function update(){
    return button.angle += 1;
  }
  onClick = function(){
    return alert("Though I'm turning around, you can still click on me");
  };
}).call(this);
