// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var chick, car, mech, robot, cop, gPreload, gCreate, addSprite, g;
  gPreload = function(){
    g.load.image('img-bunny', '../../../phaser/examples/assets/sprites/bunny.png');
    g.load.atlas('atlas', '../../../phaser/examples/assets/pics/texturepacker_test.png', '../../../phaser/examples/assets/pics/texturepacker_test.json');
  };
  gCreate = function(){
    g.stage.backgroundColor = '#404040';
    addSprite(64, 64, 'atlas', 'budbrain_chick.png');
    addSprite(600, 64, 'atlas', 'ladycop.png');
    addSprite(50, 300, 'atlas', 'robot.png');
    addSprite(100, 400, 'atlas', 'supercars_parsec.png');
    addSprite(250, 100, 'atlas', 'titan_mech.png');
  };
  addSprite = function(x, y, atlasName, frameName){
    var sprite;
    sprite = g.add.sprite(x, y, atlasName);
    sprite.frameName = frameName;
    sprite.inputEnabled = true;
    sprite.input.pixelPerfect = true;
    return sprite.input.useHandCursor = true;
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate
  });
}).call(this);
