// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, mushroom, texture;
  game = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: preload,
    create: create,
    update: update
  });
  function preload(){
    return game.load.image('mushroom', '../../../phaser/examples/assets/sprites/mushroom2.png');
  }
  function create(){
    texture = game.add.renderTexture('mousetrail', 800, 600);
    mushroom = game.add.sprite(0, 0, 'mushroom');
    mushroom.visible = false;
    mushroom.anchor.setTo(0.5, 0.5);
    return game.add.sprite(0, 0, texture);
  }
  function update(){
    return texture.render(mushroom, game.input.activePointer.position, false);
  }
}).call(this);
