// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var map, friendAndFoe, enemies, preload, create, render, createBaddie, g;
  map = require('prelude-ls').map;
  preload = function(){
    g.load.image('ufo', 'assets/sprites/ufo.png');
    return g.load.image('baddie', 'assets/sprites/space-baddie.png');
  };
  create = function(){
    friendAndFoe = g.add.group();
    enemies = g.add.group();
    friendAndFoe.create(200, 240, 'ufo');
    map(createBaddie, [0, 1, 2, 3, 4, 5, 6, 7]);
    return g.input.onTap.add(createBaddie, this);
  };
  render = function(){
    return g.debug.renderText('Tap screen or click to create new baddies.', 16, 24);
  };
  createBaddie = function(i){
    var x, y, s;
    x = 360 + Math.random() * 200;
    y = 120 + Math.random() * 200;
    return s = g.add.sprite(x, y, 'baddie');
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    render: render
  });
}).call(this);
