// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, sprite, bullets, veggies, bullet, laserSound, splatSound, scoreText, bulletTime, score, fireBullet, resetBullet, collisionHandler;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update
  });
  bulletTime = 0;
  score = 0;
  function preload(){
    game.load.image('phaser', '../../../phaser/examples/assets/phaser-dude.png');
    game.load.image('bullet', '../../../phaser/examples/assets/bullet0.png');
    game.load.audio('laser', '../../../phaser/examples/assets/laser1.mp3');
    game.load.audio('splat', '../../../phaser/examples/assets/splat1.mp3');
    return game.load.spritesheet('veggies', '../../../phaser/examples/assets/fruitnveg32wh37.png', 32, 32);
  }
  function create(){
    var i$, i, c, b;
    game.stage.backgroundColor = '#2d2d2d';
    veggies = game.add.group();
    for (i$ = 0; i$ < 50; ++i$) {
      i = i$;
      c = veggies.create(game.world.randomX, Math.random() * 500, 'veggies', game.rnd.integerInRange(0, 36));
      c.name = "veg" + i;
      c.body.immovable = true;
    }
    bullets = game.add.group();
    for (i$ = 0; i$ < 10; ++i$) {
      i = i$;
      b = bullets.create(0, 0, 'bullet');
      b.exists = false;
      b.visible = false;
      b.events.onOutOfBounds.add(resetBullet, this);
    }
    sprite = game.add.sprite(400, 550, 'phaser');
    sprite.body.collideWorldBounds = true;
    laserSound = game.add.audio('laser', 1, true);
    splatSound = game.add.audio('splat', 1, true);
    scoreText = game.add.text(16, 16, "Score: 0", {
      font: "24px Arial",
      fill: '#ffffff'
    });
    return game.input.keyboard.addKeyCapture(Phaser.Keyboard.LEFT, Phaser.Keyboard.RIGHT, Phaser.Keyboard.SPACEBAR);
  }
  function update(){
    sprite.body.velocity.x = 0;
    sprite.body.velocity.y = 0;
    if (game.input.keyboard.isDown(Phaser.Keyboard.LEFT)) {
      sprite.body.velocity.x = -200;
    } else if (game.input.keyboard.isDown(Phaser.Keyboard.RIGHT)) {
      sprite.body.velocity.x = 200;
    }
    if (game.input.keyboard.isDown(Phaser.Keyboard.SPACEBAR)) {
      fireBullet();
    }
    return game.physics.collide(bullets, veggies, collisionHandler, null, this);
  }
  fireBullet = function(){
    if (game.time.now > bulletTime) {
      bullet = bullets.getFirstExists(false);
      if (bullet) {
        bullet.reset(sprite.x + 6, sprite.y - 8);
        bullet.body.velocity.y = -300;
        bulletTime = game.time.now + 250;
        return laserSound.play('', 0, 0.05, false);
      }
    }
  };
  resetBullet = function(bullet){
    return bullet.kill();
  };
  collisionHandler = function(bullet, veggie){
    bullet.kill();
    veggie.kill();
    splatSound.play('', 0, 0.05, false);
    score += 1;
    return scoreText.setText("Score: " + score);
  };
}).call(this);
