// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var map, gamePreload, gameCreate, game;
  map = require('prelude-ls').map;
  gamePreload = function(){
    game.load.image('image-grid', '../../../phaser/examples/assets/tests/debug-grid-1920x1920.png');
    return game.load.image('image-atari1', '../../../phaser/examples/assets/sprites/atari800xl.png');
  };
  gameCreate = function(){
    var atari1;
    game.add.sprite(0, 0, 'image-grid');
    atari1 = game.add.sprite(300, 300, 'image-atari1');
    atari1.inputEnabled = true;
    atari1.input.enableDrag(true);
    return atari1.input.enableSnap(32, 32);
  };
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gamePreload,
    create: gameCreate
  });
}).call(this);
