// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, emitter, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.spritesheet('rain', assets + 'sprites/rain.png', 17, 17);
  };
  gCreate = function(){
    emitter = g.add.emitter(g.world.centerX, 0, 400);
    emitter.width = g.world.width;
    emitter.makeParticles('rain');
    emitter.maxParticleScale = 0.5;
    emitter.maxParticleScale = 0.1;
    emitter.setYSpeed(300, 500);
    emitter.setXSpeed(-5, 5);
    emitter.minRotation = 0;
    emitter.maxRotation = 0;
    emitter.start(false, 1600, 5, 0);
  };
  gUpdate = function(){};
  gRender = function(){};
  g = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
