// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, bg, filter;
  game = new Phaser.Game(800, 600, Phaser.WEBGL, '', {
    preload: preload,
    create: create,
    update: update
  });
  function preload(){
    game.load.image('s', '../../../phaser/examples/assets/pics/undersea.jpg');
    game.load.image('phaser', '../../../phaser/examples/assets/sprites/phaser.png');
    return game.load.script('filter', 'filters/CheckerWave.js');
  }
  function create(){
    var logo;
    game.add.sprite(0, 0, 's');
    bg = game.add.sprite(0, 0);
    bg.width = 800;
    bg.height = 600;
    filter = game.add.filter('CheckerWave', 800, 600);
    filter.alpha = 0.2;
    bg.filters = [filter];
    logo = game.add.sprite(game.world.centerX, 100, 'phaser');
    return logo.anchor.setTo(0.5, 0.5);
  }
  function update(){
    return filter.update();
  }
}).call(this);
