// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, map, layer, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.tilemap('mario', assets + 'tilemaps/maps/super_mario.json', null, Phaser.Tilemap.TILED_JSON);
    g.load.image('tiles', assets + 'tilemaps/tiles/super_mario.png');
  };
  gCreate = function(){
    var map, layer;
    g.stage.backgroundColor = '#787878';
    map = g.add.tilemap('mario');
    map.addTilesetImage('SuperMarioBros-World1-1', 'tiles');
    layer = map.createLayer('World1');
    layer.resizeWorld();
  };
  gUpdate = function(){};
  gRender = function(){};
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
