// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){};
  gCreate = function(){};
  gUpdate = function(){};
  gRender = function(){
    g.debug.renderText('Host Name: ' + g.net.getHostName(), g.world.centerX - 300, 20);
    g.debug.renderText('Host Name contains 192: ' + g.net.checkDomainName('192'), g.world.centerX - 300, 40);
    g.debug.renderText('Host Name contains google.com: ' + g.net.checkDomainName('google.com'), g.world.centerX - 300, 60);
    g.debug.renderText('Query string with new values: ' + g.net.updateQueryString('atari', '520'), g.world.centerX - 400, 80);
    g.debug.renderText('Query string with new values: ' + g.net.updateQueryString('amiga', '1200'), g.world.centerX - 400, 100);
    console.log('Query string: ' + g.net.getQueryString(), g.world.centerX - 300, 140);
    console.log('Query string param: ' + g.net.getQueryString('atari'), g.world.centerX - 300, 160);
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
