// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, sprite1, sprite2, collisionHandler;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update,
    render: render
  });
  function preload(){
    game.load.image('atari', '../../../phaser/examples/assets/sprites/atari130xe.png');
    return game.load.image('mushroom', '../../../phaser/examples/assets/sprites/mushroom2.png');
  }
  function create(){
    game.stage.backgroundColor = '#2d2d2d';
    sprite1 = game.add.sprite(300, 50, 'atari');
    sprite1.name = 'atari';
    sprite1.body.velocity.y = 100;
    sprite1.body.setRectangle(220, 10, 0, 0);
    sprite2 = game.add.sprite(400, 450, 'mushroom');
    sprite2.name = 'mushroom';
    return sprite2.body.immovable = true;
  }
  function update(){
    return game.physics.collide(sprite1, sprite2, collisionHandler, null, this);
  }
  collisionHandler = function(){
    return game.stage.backgroundColor = '#992d2d';
  };
  function render(){
    game.debug.renderSpriteInfo(sprite1, 32, 32);
    game.debug.renderPhysicsBody(sprite1.body);
    return game.debug.renderPhysicsBody(sprite2.body);
  }
}).call(this);
