// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var sprites, assets, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){
    g.load.spritesheet('spinner', assets + 'sprites/bluemetal_32x32x4.png', 32, 32);
  };
  gCreate = function(){
    var i$, i, x, y, s;
    sprites = g.add.group();
    for (i$ = 0; i$ < 30; ++i$) {
      i = i$;
      x = g.rnd.integerInRange(100, 700);
      y = g.rnd.integerInRange(32, 200);
      s = sprites.create(x, y, 'spinner');
      s.animations.add('spin', [0, 1, 2, 3]);
      s.play('spin', 20, true);
      s.body.velocity.x = g.rnd.integerInRange(-200, 200);
      s.body.velocity.y = g.rnd.integerInRange(-200, 200);
    }
    sprites.setAll('body.collideWorldBounds', true);
    sprites.setAll('body.bounce.x', 1);
    sprites.setAll('body.bounce.y', 1);
    sprites.setAll('body.minBounceVelocity', 0);
  };
  gUpdate = function(){
    g.physics.collide(sprites);
  };
  gRender = function(){};
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
