// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, cursors, shrooms, card, Keys;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update,
    render: render
  });
  function preload(){
    game.load.image('backdrop', '../../../phaser/examples/assets/pics/remember-me.jpg');
    return game.load.image('card', '../../../phaser/examples/assets/sprites/mana_card.png');
  }
  Keys = Phaser.Keyboard;
  function create(){
    game.world.setBounds(0, 0, 800, 600);
    game.add.sprite(0, 0, 'backdrop');
    card = game.add.sprite(200, 200, 'card');
    card.body.velocity.x = 50;
    card.scale.setTo(2, 2);
    return card.body.collideWorldBounds = true;
  }
  function update(){
    if (game.input.keyboard.isDown(Keys.LEFT)) {
      card.x -= 4;
    } else if (game.input.keyboard.isDown(Keys.RIGHT)) {
      card.x += 4;
    }
    if (game.input.keyboard.isDown(Keys.UP)) {
      return card.y -= 4;
    } else if (game.input.keyboard.isDown(Keys.DOWN)) {
      return card.y += 4;
    }
  }
  function render(){
    game.debug.renderCameraInfo(game.camera, 32, 32);
    return game.debug.renderSpriteCoords(card, 32, 400);
  }
}).call(this);
