// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var gPreload, gCreate, gUpdate, gRender, g;
  gPreload = function(){
    g.load.image('grid', '../../../phaser/examples/assets/tests/debug-grid-1920x1920.png');
    g.load.image('atari1', '../../../phaser/examples/assets/sprites/atari130xe.png');
    g.load.image('atari2', '../../../phaser/examples/assets/sprites/atari800xl.png');
  };
  gCreate = function(){
    var atari1, atari2;
    g.add.sprite(0, 0, 'grid');
    atari1 = g.add.sprite(128, 128, 'atari1');
    atari2 = g.add.sprite(256, 256, 'atari2');
    atari1.inputEnabled = true;
    atari2.inputEnabled = true;
    atari1.input.enableDrag();
    atari2.input.enableDrag();
    atari1.input.enableSnap(32, 32, true, true);
    atari2.input.enableSnap(32, 32, false, true);
  };
  gUpdate = function(){};
  gRender = function(){};
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
