// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, listener;
  game = new Phaser.Game(1200, 768, Phaser.AUTO, '', {
    preload: preload,
    create: create
  });
  function preload(){
    return game.load.image('sky', '../../../phaser/examples/assets/sky.png');
  }
  function create(){
    var image;
    image = game.add.sprite(0, 0, 'sky');
    image.inputEnabled = true;
    return image.events.onInputDown.add(listener, this);
  }
  listener = function(){
    return alert('clicked!');
  };
}).call(this);
