// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var keyOne, keyTwo, keyThree, gamePreload, gameCreate, addPhaserDude, addPhaserLogo, addPineapple, game;
  gamePreload = function(){
    game.load.image('image-phaser', '../../../phaser/examples/assets/sprites/phaser-dude.png');
    game.load.image('image-logo', '../../../phaser/examples/assets/sprites/phaser_tiny.png');
    return game.load.image('image-pineapple', '../../../phaser/examples/assets/sprites/pineapple.png');
  };
  gameCreate = function(){
    game.stage.backgroundColor = '#736357';
    keyOne = game.input.keyboard.addKey(Phaser.Keyboard.ONE);
    keyOne.onDown.add(addPhaserDude, this);
    keyTwo = game.input.keyboard.addKey(Phaser.Keyboard.TWO);
    keyTwo.onDown.add(addPhaserLogo, this);
    keyThree = game.input.keyboard.addKey(Phaser.Keyboard.THREE);
    return keyThree.onDown.add(addPineapple, this);
  };
  addPhaserDude = function(){
    return game.add.sprite(game.world.randomX, game.world.randomY, 'image-phaser');
  };
  addPhaserLogo = function(){
    return game.add.sprite(game.world.randomX, game.world.randomY, 'image-logo');
  };
  addPineapple = function(){
    return game.add.sprite(game.world.randomX, game.world.randomY, 'image-pineapple');
  };
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gamePreload,
    create: gameCreate
  });
}).call(this);
