// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var map, preload, create, render, g;
  map = require('prelude-ls').map;
  preload = function(){
    g.world.setBounds(0, 0, 1280, 800);
    g.load.image('ground', '../../../phaser/examples/assets/tests/ground-2x.png');
    g.load.image('river', '../../../phaser/examples/assets/tests/river-2x.png');
    g.load.image('sky', '../../../phaser/examples/assets/tests/sky-2x.png');
    g.load.image('cloud0', '../../../phaser/examples/assets/tests/cloud-big-2x.png');
    g.load.image('cloud1', '../../../phaser/examples/assets/tests/cloud-narrow-2x.png');
    g.load.image('cloud2', '../../../phaser/examples/assets/tests/cloud-small-2x.png');
    return g.load.spritesheet('ufo', '../../../phaser/examples/assets/sprites/ufo.png', 24, 21);
  };
  create = function(){
    var skyLayer, cloudLayer, groundLayer, spriteLayer, riverLayer, ufo;
    skyLayer = g.add.group();
    skyLayer.z = 0;
    cloudLayer = g.add.group();
    cloudLayer.z = 1;
    groundLayer = g.add.group();
    groundLayer.z = 2;
    spriteLayer = g.add.group();
    spriteLayer.z = 3;
    riverLayer = g.add.group();
    riverLayer.z = 3;
    skyLayer.create(0, 0, 'sky');
    cloudLayer.create(200, 120, 'cloud0');
    cloudLayer.create(-60, 120, 'cloud1');
    cloudLayer.create(900, 170, 'cloud2');
    groundLayer.create(0, 360, 'ground');
    riverLayer.create(0, 400, 'river');
    ufo = spriteLayer.create(360, 240, 'ufo');
    return ufo.anchor.setTo(0.5, 0.5);
  };
  render = function(){
    g.debug.renderText('layer-sky:     z = 0', 16, 20);
    g.debug.renderText('layer-cloud:   z = 1', 16, 36);
    g.debug.renderText('layer-ground:  z = 2', 16, 52);
    g.debug.renderText('layer-sprite:  z = 3', 16, 68);
    return g.debug.renderText('layer-river:   z = 4', 16, 84);
  };
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    render: render
  });
}).call(this);
