// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var map, ballsGroup, shipsGroup, preload, create, update, g;
  map = require('prelude-ls').map;
  preload = function(){
    g.load.image('ball', '../../../phaser/examples/assets/sprites/pangball.png');
    return g.load.image('arrow', '../../../phaser/examples/assets/sprites/asteroids_ship.png');
  };
  create = function(){
    var i$, i;
    ballsGroup = g.add.group();
    shipsGroup = g.add.group();
    for (i$ = 0; i$ < 20; ++i$) {
      i = i$;
      ballsGroup.create(g.world.randomX, g.world.randomY, 'ball');
      shipsGroup.create(g.world.randomX, g.world.randomY, 'arrow');
    }
    ballsGroup.forEach(function(sprite){
      if (sprite.body != null) {
        return sprite.anchor.setTo(0.5, 0.5);
      }
    });
    return ballsGroup.add(shipsGroup);
  };
  update = function(){
    ballsGroup.x += 0.8;
    shipsGroup.x += 1.6;
    ballsGroup.forEach(function(sprite){
      if (sprite.body != null) {
        sprite.rotation += 0.25;
        if (sprite.body.x >= 832) {
          sprite.body.x = -32;
          return sprite.body.y = Math.floor(Math.random() * g.world.height);
        }
      }
    });
    return shipsGroup.forEach(function(sprite){
      sprite.rotation = 0;
      if (sprite.body.x >= 812) {
        sprite.body.x = -12;
        return sprite.body.y = Math.floor(Math.random() * g.world.height);
      }
    });
  };
  g = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: preload,
    create: create,
    update: update
  });
}).call(this);
