// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, cursors, shrooms;
  game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: preload,
    create: create,
    update: update,
    render: render
  });
  function preload(){
    return game.load.image('mushroom', '../../../phaser/examples/assets/mushroom2.png');
  }
  function create(){
    var i$, i, shroom;
    game.stage.backgroundColor = '#2d2d2d';
    game.world.setBounds(0, 0, 1600, 1200);
    shrooms = game.add.group();
    for (i$ = 0; i$ < 150; ++i$) {
      i = i$;
      shroom = shrooms.create(game.world.randomX, game.world.randomY - 164, 'mushroom');
    }
    return cursors = game.input.keyboard.createCursorKeys();
  }
  function update(){
    if (cursors.up.isDown) {
      game.camera.y -= 4;
    } else if (cursors.down.isDown) {
      game.camera.y += 4;
    }
    if (cursors.left.isDown) {
      return game.camera.x -= 4;
    } else if (cursors.right.isDown) {
      return game.camera.x += 4;
    }
  }
  function render(){
    return game.debug.renderCameraInfo(game.camera, 32, 32);
  }
}).call(this);
