// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var assets, gPreload, gCreate, gUpdate, gRender, g;
  assets = '../../../phaser/examples/assets/';
  gPreload = function(){};
  gCreate = function(){
    g.rnd.sow([123]);
    console.log('A');
    console.log(g.rnd.integer());
    console.log(g.rnd.integer());
    console.log(g.rnd.integer());
    console.log(g.rnd.integer());
    console.log(g.rnd.integer());
    g.rnd.sow([0]);
    console.log('B');
    console.log(g.rnd.integer());
    console.log(g.rnd.integer());
    console.log(g.rnd.integer());
    console.log(g.rnd.integer());
    console.log(g.rnd.integer());
    g.rnd.sow([123]);
    console.log('C');
    console.log(g.rnd.integer());
    console.log(g.rnd.integer());
    console.log(g.rnd.integer());
    console.log(g.rnd.integer());
    console.log(g.rnd.integer());
  };
  gUpdate = function(){};
  gRender = function(){};
  g = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    preload: gPreload,
    create: gCreate,
    update: gUpdate,
    render: gRender
  });
}).call(this);
